# Generated by Django 4.2.30 on 2026-07-19 00:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department_management', '0001_initial'),
        ('lecturer_portal', '0001_initial'),
        ('program_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampusCourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('academic_year', models.CharField(blank=True, default='', help_text='Academic year, e.g. 2024/2025', max_length=20)),
                ('allocation_semester', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2')], help_text='Semester in which this course is allocated (1 or 2)', null=True)),
                ('program_year', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5'), (6, 'Year 6')], help_text='Program year this course belongs to (1-6)', null=True)),
                ('is_special_course', models.BooleanField(default=False, help_text='Special/extra course not part of the standard curriculum')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('number_of_students', models.PositiveIntegerField(default=0)),
                ('approved_by_dvc', models.BooleanField(default=False)),
                ('rejected_by_dvc', models.BooleanField(default=False)),
                ('reason_for_disapproval', models.TextField(blank=True, default='No reason yet')),
                ('submitted_to_tt', models.BooleanField(default=False)),
                ('delivery_mode', models.CharField(choices=[('PHYSICAL', 'Physical'), ('ONLINE', 'Online'), ('BLENDED', 'Blended')], default='PHYSICAL', max_length=20)),
                ('campus', models.ForeignKey(help_text='Campus this course is allocated to. Required.', on_delete=django.db.models.deletion.PROTECT, related_name='course_allocations', to='campuses_timetable.campus')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_allocations', to='department_management.department')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_course_allocations', to='lecturer_portal.lecturer')),
                ('origin_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_origin_allocations', to='department_management.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_allocations', to='program_management.program')),
                ('program_course', models.ForeignKey(blank=True, help_text='The ProgramCourse (curriculum entry) this campus allocation is derived from. Required — deleting the ProgramCourse removes this allocation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_course_allocations', to='program_management.programcourse')),
                ('teaching_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_allocations', to='campuses_timetable.campus')),
            ],
            options={
                'permissions': [('approve_course_allocation', 'Can approve course allocation (DVC only)'), ('forward_course_allocation', 'Can forward course allocation to timetable (COD only)')],
                'unique_together': {('program', 'course_code', 'campus')},
            },
        ),
        migrations.CreateModel(
            name='CampusLabAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_allocations', to='campuses_timetable.campus')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecturer_portal.lecturer')),
                ('program_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_lab_allocations', to='program_management.programcourse')),
            ],
        ),
        migrations.CreateModel(
            name='CampusTimetableTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('CLASS', 'Class Timetable'), ('EXAM', 'Exam Timetable'), ('COURSE_ALLOCATION', 'Course Allocation')], max_length=20, unique=True)),
                ('university_name', models.CharField(default='CHUKA UNIVERSITY', max_length=200)),
                ('directorate_name', models.CharField(default='DIRECTORATE OF CAMPUS TIMETABLE', max_length=200)),
                ('address', models.CharField(default='P.O. Box 109-60400, Chuka', max_length=200)),
                ('telephone', models.CharField(default='020-231 0512/0721-712 609', max_length=50)),
                ('email', models.EmailField(default='info@chuka.ac.ke', max_length=254)),
                ('website', models.URLField(default='www.chuka.ac.ke')),
                ('motto_latin', models.CharField(default='Scientia ad Excelsitudinem', max_length=200)),
                ('motto_swahili', models.CharField(default='Elimu ya Malidadi', max_length=200)),
                ('university_logo', models.ImageField(blank=True, null=True, upload_to='timetable_templates/logos/')),
                ('title_format', models.CharField(default='{timetable_type} TIMETABLE', help_text='Use {timetable_type} placeholder', max_length=200)),
                ('reference_format', models.CharField(default='CU/DIR/TT/{date}/REF', help_text='Reference number format', max_length=100)),
                ('key_section', models.TextField(default='KEY:', help_text='Key/Legend text to appear at the end')),
                ('prepared_by_label', models.CharField(default='Prepared by:', max_length=100)),
                ('director_label', models.CharField(default='DIRECTOR, CAMPUS TIMETABLE', max_length=100)),
                ('primary_color', models.CharField(default='#2e7d32', help_text='Primary color (hex)', max_length=20)),
                ('secondary_color', models.CharField(default='#43a047', help_text='Secondary color (hex)', max_length=20)),
                ('accent_color', models.CharField(default='#4caf50', help_text='Accent color (hex)', max_length=20)),
                ('page_header_format', models.CharField(default='Page {current_page} of {total_pages}', help_text='Use {current_page} and {total_pages} placeholders', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timetable Template',
                'verbose_name_plural': 'Timetable Templates',
            },
        ),
        migrations.CreateModel(
            name='ProgramYearTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_year', models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5'), (6, 'Year 6')])),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')])),
                ('academic_year', models.CharField(help_text='e.g. 2024/2025', max_length=20)),
                ('expected_courses', models.JSONField(default=list)),
                ('allocated_courses', models.JSONField(default=list)),
                ('missing_courses', models.JSONField(default=list)),
                ('carryover_missing', models.JSONField(default=list)),
                ('is_complete', models.BooleanField(default=False, help_text='True when all expected courses have been allocated')),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_trackers', to='program_management.program')),
            ],
            options={
                'verbose_name': 'Program Year Tracker',
                'verbose_name_plural': 'Program Year Trackers',
                'ordering': ['program', 'program_year', 'semester'],
                'unique_together': {('program', 'program_year', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='CampusSchedulerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(7, 0))),
                ('end_time', models.TimeField(default=datetime.time(19, 0))),
                ('slot_size', models.PositiveIntegerField(default=3)),
                ('campus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_config', to='campuses_timetable.campus')),
            ],
            options={
                'verbose_name': 'Campus Scheduler Configuration',
                'verbose_name_plural': 'Campus Scheduler Configurations',
            },
        ),
        migrations.CreateModel(
            name='CampusExamSchedulerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default=datetime.time(8, 0))),
                ('end_time', models.TimeField(default=datetime.time(17, 0))),
                ('slot_size', models.PositiveIntegerField(default=2)),
                ('excluded_days', models.TextField(blank=True, default='')),
                ('max_exam_days', models.PositiveIntegerField(default=14)),
                ('spacing_ratio', models.FloatField(default=0.7)),
                ('campus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_scheduler_config', to='campuses_timetable.campus')),
            ],
        ),
        migrations.CreateModel(
            name='CampusArchivedCourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=32)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('number_of_students', models.PositiveIntegerField(default=0)),
                ('approved_by_dvc', models.BooleanField(default=False)),
                ('rejected_by_dvc', models.BooleanField(default=False)),
                ('reason_for_disapproval', models.TextField(blank=True, default='No reason yet')),
                ('submitted_to_tt', models.BooleanField(default=False)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_allocations', to='campuses_timetable.campus')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_archived_allocations', to='department_management.department')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecturer_portal.lecturer')),
                ('origin_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_archived_origin_allocations', to='department_management.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program_management.program')),
            ],
            options={
                'verbose_name': 'Campus Archived Course Allocation',
                'verbose_name_plural': 'Campus Archived Course Allocations',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationGapReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_gap_reports', to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_reports', to='campuses_timetable.programyeartracker')),
            ],
            options={
                'verbose_name': 'Allocation Gap Report',
                'verbose_name_plural': 'Allocation Gap Reports',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CampusTimetableArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable_type', models.CharField(choices=[('MAIN', 'Main Timetable'), ('EXAM', 'Exam Timetable'), ('LAB', 'Lab Timetable'), ('LAB_EXAM', 'Lab Exam Timetable')], max_length=20)),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester')], max_length=2)),
                ('academic_year', models.CharField(max_length=15)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField()),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_archives', to='campuses_timetable.campus')),
            ],
            options={
                'ordering': ['-archived_at'],
                'unique_together': {('semester', 'academic_year', 'timetable_type', 'campus')},
            },
        ),
        migrations.CreateModel(
            name='CampusTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='campuses_timetable.campus')),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='campuses_timetable.campuscourseallocation')),
            ],
            options={
                'permissions': [('approve_timetable', 'Can approve timetable')],
                'unique_together': {('course_allocation', 'day', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='CampusTempTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_timetables', to='campuses_timetable.campus')),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_timetable_entries', to='campuses_timetable.campuscourseallocation')),
            ],
            options={
                'unique_together': {('course_allocation', 'day', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='CampusSubmissionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_submission_to_dvc', models.BooleanField(default=True)),
                ('allow_submission_to_tt', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_controls', to='campuses_timetable.campus')),
                ('department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_submission_control', to='department_management.department')),
            ],
            options={
                'verbose_name': 'Campus Submission Control',
                'verbose_name_plural': 'Campus Submission Controls',
                'unique_together': {('department', 'campus')},
            },
        ),
        migrations.CreateModel(
            name='CampusPublishedTimetablePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable_type', models.CharField(choices=[('CLASS', 'Class Timetable'), ('EXAM', 'Exam Timetable')], max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(upload_to='campus_timetables/published/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_timetables', to='campuses_timetable.campus')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_published_timetables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Published Campus Timetable',
                'verbose_name_plural': 'Published Campus Timetables',
                'ordering': ['-published_at'],
                'unique_together': {('timetable_type', 'version', 'campus')},
            },
        ),
        migrations.CreateModel(
            name='CampusLabTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=16)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_timetables', to='campuses_timetable.campus')),
                ('lab_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_timetables', to='campuses_timetable.campuslaballocation')),
            ],
            options={
                'unique_together': {('lab_allocation', 'day', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='CampusLabExamTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('day', models.CharField(max_length=16)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_exam_timetables', to='campuses_timetable.campus')),
                ('lab_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_exam_timetables', to='campuses_timetable.campuslaballocation')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('lab_allocation', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='CampusExamTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_timetables', to='campuses_timetable.campus')),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_timetable_entries', to='campuses_timetable.campuscourseallocation')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'permissions': [('approve_timetable', 'Can approve timetable')],
                'unique_together': {('course_allocation', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='CampusExamTempTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_temp_timetables', to='campuses_timetable.campus')),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_temp_timetable_entries', to='campuses_timetable.campuscourseallocation')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('course_allocation', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
