# Generated by Django 4.2.30 on 2026-08-07 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0003_alter_venueblock_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resits_timetabling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResitVenueExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', help_text="Why this venue/building is excluded from resits, e.g. 'Reserved for Senate sittings'.", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily lift the exclusion without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, help_text='Exclude every venue in this building from the resit auto-scheduler.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resit_exclusions', to='room_management.building')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resit_venue_exclusions_created', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, help_text='Exclude this specific venue from the resit auto-scheduler.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resit_exclusions', to='room_management.venue')),
            ],
            options={
                'verbose_name': 'Resit Venue Exclusion',
                'verbose_name_plural': 'Resit Venue Exclusions',
                'ordering': ['building__name', 'venue__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='resitvenueexclusion',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('building__isnull', False), ('venue__isnull', True)), models.Q(('building__isnull', True), ('venue__isnull', False)), _connector='OR'), name='resit_venue_exclusion_building_xor_venue'),
        ),
        migrations.AddConstraint(
            model_name='resitvenueexclusion',
            constraint=models.UniqueConstraint(condition=models.Q(('venue__isnull', True)), fields=('building',), name='unique_resit_building_exclusion'),
        ),
        migrations.AddConstraint(
            model_name='resitvenueexclusion',
            constraint=models.UniqueConstraint(condition=models.Q(('building__isnull', True)), fields=('venue',), name='unique_resit_venue_exclusion'),
        ),
    ]
