# Generated by Django 4.2.30 on 2026-07-19 00:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly label, e.g. 'Gemini Flash (default)' or 'Office Ollama'.", max_length=80)),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('ollama', 'Ollama (local / self-hosted)'), ('custom', 'OpenAI-compatible endpoint (DeepSeek, BlackBox, Groq, OpenRouter, Mistral, Together, xAI/Grok, Fireworks, Perplexity, LM Studio, vLLM, etc.)'), ('generic', 'Generic / fully custom API (any provider, any shape — no code changes)')], max_length=20)),
                ('model_name', models.CharField(help_text="Model identifier the provider expects, e.g. 'gemini-2.5-flash', 'gpt-4o-mini', 'claude-sonnet-4-6', 'llama3'.", max_length=120)),
                ('api_key_encrypted', models.TextField(blank=True, default='', help_text="Stored encrypted. Leave blank for providers that don't need a key (e.g. local Ollama).")),
                ('base_url', models.URLField(blank=True, default='', help_text="For 'custom' (OpenAI-compatible): the base URL, e.g. https://api.deepseek.com/v1 — see the provider field's help text for presets. For 'generic': the FULL endpoint URL to POST to. For self-hosted Ollama: only needed if not on the default local address.")),
                ('is_active', models.BooleanField(default=False, help_text='Only one provider can be active at a time. Activating this one deactivates all others. Leave all inactive to disable AI features everywhere (modules fall back to normal non-AI behaviour).')),
                ('request_timeout_seconds', models.PositiveIntegerField(default=60)),
                ('generic_http_method', models.CharField(default='POST', help_text='HTTP method for the request. Almost always POST.', max_length=10)),
                ('generic_headers_template', models.TextField(blank=True, default='{\n  "Content-Type": "application/json",\n  "Authorization": "Bearer {{api_key}}"\n}', help_text='JSON object of request headers. Use {{api_key}} anywhere the key belongs (e.g. in an Authorization or x-api-key header).')),
                ('generic_body_template', models.TextField(blank=True, default='{\n  "model": "{{model}}",\n  "messages": [{"role": "user", "content": "{{prompt}}"}]\n}', help_text='JSON request body template. Use {{model}} and {{prompt}} as placeholders — they are safely substituted as JSON strings (no manual escaping needed).')),
                ('generic_response_text_path', models.CharField(blank=True, default='choices.0.message.content', help_text="Dotted path to the generated text inside the JSON response, e.g. 'choices.0.message.content' (OpenAI-style), 'content.0.text' (Anthropic-style), or 'candidates.0.content.parts.0.text' (Gemini-style).", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider Setting',
                'verbose_name_plural': 'AI Provider Settings',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site/photos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])])),
                ('caption', models.CharField(blank=True, help_text='Optional caption shown on the carousel slide.', max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Screen-reader description of the image.', max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first in the carousel.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide without deleting.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Photo',
                'verbose_name_plural': 'Site Photos',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(default='Chuka University', help_text='Full university name shown in the navbar and page titles.', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Excellence in Learning', help_text='Short motto or tagline shown in the hero section.', max_length=300)),
                ('logo', models.ImageField(blank=True, help_text='University crest/logo. Recommended: transparent PNG, min 200×200 px.', null=True, upload_to='site/logo/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg', 'webp'])])),
                ('contact_email', models.EmailField(blank=True, default='info@chuka.ac.ke', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=60)),
                ('contact_location', models.CharField(blank=True, default='Science Complex (S102), Main Campus', max_length=200)),
                ('website_url', models.URLField(blank=True, default='https://www.chuka.ac.ke')),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='OrgRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CotUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cot_users', to='department_management.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cot_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
