# Generated by Django 4.2.30 on 2026-08-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0003_alter_venueblock_id'),
        ('core', '0003_scheduling_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerblockedslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecturertimepreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecturervenuepreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecturervenuepreference',
            name='venues',
            field=models.ManyToManyField(help_text='One or more venues this lecturer prefers to be scheduled in.', related_name='lecturer_preferences', to='room_management.venue'),
        ),
        migrations.AlterField(
            model_name='schedulerconstrainttoggle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
