# Generated by Django 4.2.30 on 2026-08-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lecturerblockedslot_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturertimepreference',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='lecturervenuepreference',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='lecturervenuepreference',
            name='venues',
        ),
        migrations.DeleteModel(
            name='LecturerBlockedSlot',
        ),
        migrations.DeleteModel(
            name='LecturerTimePreference',
        ),
        migrations.DeleteModel(
            name='LecturerVenuePreference',
        ),
    ]
