# Generated by Django 4.2.30 on 2026-08-31 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_sync_host_remote'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='syncrecordstate',
            new_name='core_syncre_app_lab_42f6f9_idx',
            old_name='core_syncre_app_lab_9b6f7f_idx',
        ),
        migrations.AlterField(
            model_name='syncmodellog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='syncmodellog',
            name='order',
            field=models.PositiveIntegerField(help_text='Position in the dependency-safe send order.'),
        ),
        migrations.AlterField(
            model_name='syncnode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='syncnode',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Master on/off switch. Leave off until both sides are configured with the same shared token.'),
        ),
        migrations.AlterField(
            model_name='syncnode',
            name='mode',
            field=models.CharField(choices=[('host', 'Host — sends data to a remote'), ('remote', 'Remote — receives data from a host')], default='host', help_text='Whether this installation is the HOST (sends data out) or the REMOTE (receives data from a host).', max_length=10),
        ),
        migrations.AlterField(
            model_name='syncnode',
            name='remote_url',
            field=models.URLField(blank=True, default='', help_text='HOST ONLY: base URL of the remote installation to sync to, e.g. https://backup.example.ac.ke — the /export-import/sync/receive/ path is appended automatically.'),
        ),
        migrations.AlterField(
            model_name='syncnode',
            name='shared_token_encrypted',
            field=models.TextField(blank=True, default='', help_text='Shared secret used to authenticate sync requests. Stored encrypted. Must match on both the host and the remote.'),
        ),
        migrations.AlterField(
            model_name='syncnode',
            name='sync_batch_delay_seconds',
            field=models.FloatField(default=1.5, help_text="Pause between sending each model's batch during a sync run. Keeps a long sync from hammering the remote server or the network all at once, and keeps the background worker from hanging."),
        ),
        migrations.AlterField(
            model_name='syncrecordstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='peer_run_id',
            field=models.CharField(blank=True, default='', help_text="On the HOST: not used. On the REMOTE: the host's SyncRun id for this push batch, so incoming model logs from the same sync run can be grouped together here even though the two sides have separate SyncRun tables.", max_length=64),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, help_text="Superuser who clicked 'Sync Now', or blank for an automated run.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
