# Generated by Django 4.2.30 on 2026-09-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_core_syncre_app_lab_9b6f7f_idx_core_syncre_app_lab_42f6f9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncnode',
            name='last_connection_check_at',
            field=models.DateTimeField(blank=True, help_text='HOST ONLY: last time this installation actively tested connectivity to the configured remote (a lightweight ping, not a data push).', null=True),
        ),
        migrations.AddField(
            model_name='syncnode',
            name='last_connection_error',
            field=models.TextField(blank=True, default='', help_text='HOST ONLY: error message from the last failed connection check.'),
        ),
        migrations.AddField(
            model_name='syncnode',
            name='last_connection_ok',
            field=models.BooleanField(blank=True, default=None, help_text='HOST ONLY: result of the last connection check.', null=True),
        ),
        migrations.AddField(
            model_name='syncnode',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, help_text='REMOTE ONLY: last time a host successfully reached this installation with a valid shared token (a ping or an actual sync push both count).', null=True),
        ),
    ]
