# Generated by Django 4.2.30 on 2026-09-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_syncnode_last_connection_check_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncnode',
            name='pinned_cert_fingerprint',
            field=models.CharField(blank=True, default='', help_text="HOST ONLY: SHA-256 fingerprint (hex) of the remote's TLS certificate, pinned via the 'Certificate Pinning' panel. When set, this is checked on every connection instead of the system CA trust store — the modern, safer alternative to turning Verify SSL off for a self-signed remote.", max_length=64),
        ),
        migrations.AddField(
            model_name='syncnode',
            name='pinned_cert_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncnode',
            name='verify_ssl',
            field=models.BooleanField(default=True, help_text="HOST ONLY: verify the remote's TLS certificate against the system's trusted CA list. Leave ON in production. Ignored once a certificate fingerprint is pinned below — pinning is the stronger, recommended way to trust a self-signed/internal remote."),
        ),
    ]
