# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_syncnode_pinned_cert_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncnode',
            name='auto_sync_interval_minutes',
            field=models.PositiveIntegerField(
                default=0,
                help_text="HOST ONLY: how often to automatically run a sync in the background, "
                          "in minutes. 0 means sync only happens when someone clicks 'Sync Now' "
                          "(or runs the sync_now management command) — nothing runs on its own, "
                          "including after a network drop and reconnect. Set this above 0 to have "
                          "the scheduler (Celery Beat) push changes automatically on that cadence.",
            ),
        ),
    ]
