# Generated by Django 4.2.30 on 2026-09-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_syncmodellog_partial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncnode',
            name='auto_sync_interval_minutes',
            field=models.PositiveIntegerField(default=0, help_text="HOST ONLY: as long as sync is enabled and configured, this installation already auto-syncs the moment it detects the remote has come back online (checked every couple of minutes in the background) — that part is always on. This setting is ADDITIONALLY how often to also resync on a fixed schedule even while the connection never drops, in minutes. 0 means no extra scheduled resync — only the reconnect-triggered one above, plus whatever you trigger manually with 'Sync Now' or the sync_now command."),
        ),
    ]
