# Generated by Django 4.2.30 on 2026-09-10 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_syncnode_auto_sync_interval_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_apk',
            field=models.FileField(blank=True, help_text="The Android app (.apk) students download. Can be a large file (tens of MB) — make sure the web server's upload size limit allows it (see docker/nginx/default.conf's client_max_body_size).", null=True, upload_to='site/app/', validators=[django.core.validators.FileExtensionValidator(['apk'])]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_apk_version',
            field=models.CharField(blank=True, help_text="Optional version label shown next to the download link, e.g. '1.4.2'.", max_length=30),
        ),
    ]
