# Generated by Django 4.2.30 on 2026-09-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_mobile_apk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncmodellog',
            options={'ordering': ['run', 'order', 'pass_number'], 'verbose_name': 'Sync Model Log', 'verbose_name_plural': 'Sync Model Logs'},
        ),
        migrations.AddField(
            model_name='syncmodellog',
            name='pass_number',
            field=models.PositiveIntegerField(default=1, help_text='Which automatic pass (within the same SyncRun) produced this line. A model that failed on pass 1 and succeeded on an automatic retry pass 2 shows up here as two rows, one per pass, so the history of what actually happened is visible rather than overwritten.'),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='pass_count',
            field=models.PositiveIntegerField(default=1, help_text="How many automatic passes this run made over the model list. A run that fails to fully send everything on its first pass is automatically retried in place (same SyncRun, no re-click needed) as long as later passes are still making forward progress — this is how many it took, whether that's 1 (fully sent first try) or up to sync_engine.MAX_SYNC_PASSES."),
        ),
    ]
