# Generated by Django 4.2.30 on 2026-07-19 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty_management', '0001_initial'),
        ('department_management', '0001_initial'),
        ('program_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_workshop', models.BooleanField(default=False, help_text='Designates whether this building is a workshop facility.')),
                ('faculty', models.ForeignKey(blank=True, help_text='Faculty this building belongs to (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='faculty_management.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='LabVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('equipment', models.TextField(blank=True, help_text='List of lab equipment or resources', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('exam_capacity', models.PositiveIntegerField(blank=True, help_text='Capacity specifically for exam seating arrangements', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_workshop', models.BooleanField(default=False, help_text='Designates whether this venue is a workshop room.')),
                ('is_specialized', models.BooleanField(default=False, help_text='When True, this venue is reserved for courses/programs assigned via VenueSpecialization rules. The scheduler will fill these rooms with their designated courses first; other courses may only use the venue once all its designated courses have been scheduled.')),
                ('building', models.ForeignKey(blank=True, default=None, help_text='Building this venue belongs to (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='room_management.building')),
            ],
        ),
        migrations.CreateModel(
            name='VenueSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A human-readable label for this specialization rule, e.g. 'CS Lab rooms — Year 3'.", max_length=200)),
                ('scope', models.CharField(choices=[('department', 'Department (all programs & courses)'), ('program', 'Program (all courses in program)'), ('course', 'Individual Courses'), ('mixed', 'Mixed (programs + individual courses)')], default='course', help_text='Broadest targeting level for this rule.', max_length=20)),
                ('strict', models.BooleanField(default=False, help_text='If True, designated courses MUST be placed in one of the listed venues (they will be marked unschedulable if no designated venue is free). If False (soft reservation), designated courses are placed in these venues first but may fall back to any venue when all designated venues are occupied.')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Lower number = higher priority when multiple rules match a course.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, help_text='Specific individual courses designated to the selected venues.', related_name='venue_specializations', to='program_management.programcourse')),
                ('departments', models.ManyToManyField(blank=True, help_text='Courses from ALL programs in these departments will be designated.', related_name='venue_specializations', to='department_management.department')),
                ('programs', models.ManyToManyField(blank=True, help_text='All courses within these programs will be designated.', related_name='venue_specializations', to='program_management.program')),
                ('venues', models.ManyToManyField(help_text='One or more venues reserved for the designated courses.', related_name='specializations', to='room_management.venue')),
            ],
            options={
                'verbose_name': 'Venue Specialization',
                'verbose_name_plural': 'Venue Specializations',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
