# Generated by Django 4.2.30 on 2026-08-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0002_venuespecialization_exclusive_venueblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueblock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
