# Generated by Django 4.2.30 on 2026-08-01 14:51

import allocation_reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation_reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='allocationpdfrun',
            new_name='allocation__scope_725f63_idx',
            old_name='alloc_pdf_scope_dept_idx',
        ),
        migrations.AlterField(
            model_name='allocationpdfrun',
            name='file',
            field=models.FileField(blank=True, max_length=400, null=True, upload_to=allocation_reports.models.allocation_pdf_upload_path),
        ),
    ]
