# Generated by Django 4.2.30 on 2026-09-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='announcement',
            new_name='mobile_api__is_publ_ed8883_idx',
            old_name='mobile_api__is_publ_5c3a1a_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='mobile_api__program_74f2c0_idx',
            old_name='mobile_api__program_9d2b4e_idx',
        ),
    ]
