# Generated by Django 4.2.30 on 2026-09-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0003_personalcourseentry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='personalcourseentry',
            new_name='mobile_api__role_745067_idx',
            old_name='mobile_api__role_c47b57_idx',
        ),
        migrations.RenameIndex(
            model_name='personalcourseentry',
            new_name='mobile_api__role_f15cf7_idx',
            old_name='mobile_api__role_b19f4a_idx',
        ),
    ]
