# Generated by hand, matching the style of the other mobile_api migrations.

from django.db import migrations, models


def seed_rows(apps, schema_editor):
    # So both rows show up in admin right away instead of only appearing
    # lazily the first time the mobile API touches ScheduleVisibility.get_for.
    ScheduleVisibility = apps.get_model('mobile_api', 'ScheduleVisibility')
    for schedule_type in ('main', 'exam'):
        ScheduleVisibility.objects.get_or_create(schedule_type=schedule_type)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0004_rename_mobile_api__role_c47b57_idx_mobile_api__role_745067_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(
                    choices=[('main', 'Regular timetable'), ('exam', 'Exam timetable')],
                    max_length=10, unique=True,
                )),
                ('is_blocked', models.BooleanField(
                    default=False,
                    help_text="When ON, the mobile app hides this schedule's grid and shows the "
                              "message/link below instead of the timetable data.",
                )),
                ('message', models.TextField(
                    blank=True, default='',
                    help_text="Shown to students/lecturers in place of the schedule while blocked, "
                              "e.g. 'The exam timetable is being finalised and will be published shortly.'",
                )),
                ('link_label', models.CharField(
                    blank=True, default='', max_length=100,
                    help_text="Text on the tappable link/button shown under the message, e.g. "
                              "'Download provisional timetable (PDF)'. Leave blank to show no link.",
                )),
                ('link_url', models.URLField(
                    blank=True, default='',
                    help_text='Where the link goes, e.g. a PDF uploaded elsewhere on the site. '
                              'Opened (and downloaded, for a PDF) on the device when tapped.',
                )),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobile schedule visibility',
                'verbose_name_plural': 'Mobile schedule visibility',
                'ordering': ['schedule_type'],
            },
        ),
        migrations.RunPython(seed_rows, noop_reverse),
    ]
