# Generated by hand, matching the style of the other mobile_api migrations.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0005_schedulevisibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInstall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(
                    help_text="Device-generated identifier the app persists locally so it never reports the same install twice.",
                    max_length=200, unique=True,
                )),
                ('platform', models.CharField(
                    choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('other', 'Other')],
                    default='other', max_length=10,
                )),
                ('app_version', models.CharField(blank=True, default='', max_length=30)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobile app install',
                'verbose_name_plural': 'Mobile app installs',
                'ordering': ['-first_seen_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deviceinstall',
            index=models.Index(fields=['platform'], name='mobapi_devinst_platform_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinstall',
            index=models.Index(fields=['first_seen_at'], name='mobapi_devinst_firstseen_idx'),
        ),
    ]
