# Generated by Django 4.2.30 on 2026-07-19 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(choices=[('Prof', 'Prof.'), ('Dr', 'Dr.'), ('Mr', 'Mr.'), ('Ms', 'Ms.'), ('Mrs', 'Mrs.')], max_length=10)),
                ('max_load_override', models.PositiveSmallIntegerField(blank=True, help_text='Optional per-lecturer override of max courses PER SEMESTER (seniority handling, e.g. a senior lecturer/Prof = 8, a junior/part-time lecturer = 4). Leave blank to fall back to the department/global AllocationConfig default.', null=True)),
                ('department', models.ForeignKey(blank=True, default=None, help_text='Department the lecturer belongs to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='department_management.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='lecturer_po_name_4c5efb_idx')],
            },
        ),
    ]
