# Generated by Django 4.2.30 on 2026-07-19 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable_type', models.CharField(choices=[('REGULAR', 'Regular Timetable'), ('EXAM', 'Exam Timetable')], max_length=10)),
                ('academic_year', models.CharField(help_text='e.g. 2024/2025', max_length=15)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2')], max_length=2)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.CharField(blank=True, max_length=150)),
                ('is_latest', models.BooleanField(db_index=True, default=True)),
                ('pdf_document_id', models.PositiveIntegerField(blank=True, help_text='ID of the export_import.PDFDocument that triggered this publication', null=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('admission_number', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('unseen', 'Unseen'), ('seen', 'Seen'), ('attended', 'Attended'), ('solved', 'Solved')], default='unseen', max_length=20)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=128)),
                ('user_message', models.TextField()),
                ('bot_reply', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=80)),
                ('query_type', models.CharField(blank=True, max_length=40)),
                ('bot_failed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Chat Conversation Log',
                'verbose_name_plural': 'Chat Conversation Logs',
                'db_table': 'feedback_chatconversationlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='feedback_ch_created_1c5ecb_idx'), models.Index(fields=['bot_failed', 'created_at'], name='feedback_ch_bot_fai_199825_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatbotTimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue_code', models.CharField(blank=True, max_length=50)),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('course_code', models.CharField(db_index=True, max_length=100)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('program_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('department_name', models.CharField(blank=True, max_length=200)),
                ('year_of_study', models.CharField(blank=True, max_length=5)),
                ('lecturer_name', models.CharField(blank=True, max_length=200)),
                ('merged_codes', models.TextField(blank=True, help_text="Comma-separated list of all codes sharing this slot (including this entry's own code)")),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='feedback.chatbotpublication')),
            ],
        ),
        migrations.AddIndex(
            model_name='chatbotpublication',
            index=models.Index(fields=['timetable_type', 'academic_year', 'semester', 'is_latest'], name='feedback_ch_timetab_e0bcf9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbottimetableentry',
            index=models.Index(fields=['publication', 'course_code'], name='feedback_ch_publica_452879_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbottimetableentry',
            index=models.Index(fields=['publication', 'program_name'], name='feedback_ch_publica_b55859_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbottimetableentry',
            index=models.Index(fields=['publication', 'day', 'start_time'], name='feedback_ch_publica_a30a37_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbottimetableentry',
            index=models.Index(fields=['publication', 'venue_code'], name='feedback_ch_publica_2ebc41_idx'),
        ),
    ]
