# Generated by Django 4.2.30 on 2026-08-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programcourse',
            options={'ordering': ['program', '-intake_year', 'year', 'semester', 'course_code']},
        ),
        migrations.AlterUniqueTogether(
            name='programcourse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='program',
            name='default_intake_year',
            field=models.PositiveIntegerField(default=0, help_text='Default intake year for new students. 0 = legacy curriculum.'),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='intake_year',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Intake year this course applies to. 0 = legacy curriculum. Use 4-digit year (e.g., 2024)'),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='unit_type',
            field=models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('UNIVERSITY_WIDE', 'University Wide'), ('REQUIRED_ELECTIVE', 'Required Elective')], default='CORE', help_text='Type of course unit: Core, Elective, University Wide, or Required Elective', max_length=20),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='programcourse',
            unique_together={('program', 'course_code', 'intake_year')},
        ),
        migrations.AddIndex(
            model_name='programcourse',
            index=models.Index(fields=['program', 'intake_year'], name='program_man_program_41886e_idx'),
        ),
        migrations.AddIndex(
            model_name='programcourse',
            index=models.Index(fields=['program', 'intake_year', 'semester'], name='program_man_program_febdad_idx'),
        ),
    ]
