# Generated by Django 4.2.30 on 2026-08-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0002_alter_programcourse_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programcourse',
            options={'ordering': ['program', '-student_cohort', 'year', 'semester', 'course_code']},
        ),
        migrations.RemoveIndex(
            model_name='programcourse',
            name='program_man_program_41886e_idx',
        ),
        migrations.RemoveIndex(
            model_name='programcourse',
            name='program_man_program_febdad_idx',
        ),
        migrations.AlterUniqueTogether(
            name='programcourse',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='program',
            name='default_intake_year',
        ),
        migrations.AddField(
            model_name='program',
            name='default_cohort',
            field=models.CharField(default='0', help_text="Default cohort for new students (e.g., '2024', '2024/2025', 'LEGACY')", max_length=20),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='student_cohort',
            field=models.CharField(db_index=True, default='0', help_text="Student cohort this curriculum applies to. '0' = legacy, '2024', '2024/2025', etc.", max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='programcourse',
            unique_together={('program', 'course_code', 'student_cohort')},
        ),
        migrations.AddIndex(
            model_name='programcourse',
            index=models.Index(fields=['program', 'student_cohort'], name='program_man_program_68c898_idx'),
        ),
        migrations.AddIndex(
            model_name='programcourse',
            index=models.Index(fields=['program', 'student_cohort', 'semester'], name='program_man_program_be8c13_idx'),
        ),
        migrations.RemoveField(
            model_name='programcourse',
            name='intake_year',
        ),
    ]
