# Generated by Django 4.2.30 on 2026-08-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0005_importjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importjob',
            new_name='program_man_status_31190c_idx',
            old_name='program_man_status_e5b1a1_idx',
        ),
        migrations.RenameIndex(
            model_name='importjob',
            new_name='program_man_created_b4d68f_idx',
            old_name='program_man_created_9e3c2f_idx',
        ),
    ]
