# Generated by Django 4.2.30 on 2026-09-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0006_rename_program_man_status_e5b1a1_idx_program_man_status_31190c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcourse',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3')], default=1),
        ),
    ]
