# Generated by Django 4.2.30 on 2026-07-29 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('location', models.CharField(blank=True, default='', help_text="Free-text location, e.g. building/floor (e.g. 'Admin Block, 2nd Floor').", max_length=200)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('venue_type', models.CharField(choices=[('hall', 'Meeting Hall'), ('boardroom', 'Boardroom'), ('conference', 'Conference Room'), ('workshop', 'Workshop'), ('lab', 'Lab'), ('other', 'Other')], default='hall', max_length=20)),
                ('is_workshop', models.BooleanField(default=False, help_text='Designates this meeting venue as a workshop facility.')),
                ('is_lab', models.BooleanField(default=False, help_text='Designates this meeting venue as a lab facility.')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to retire this venue from use without deleting its booking history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meeting Venue',
                'verbose_name_plural': 'Meeting Venues',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MeetingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.CharField(help_text='Name / department / office of whoever booked this venue.', max_length=200)),
                ('booked_for', models.CharField(help_text="Purpose or title of the meeting, e.g. 'Senate Meeting', 'Staff Briefing'.", max_length=255)),
                ('contact', models.CharField(blank=True, default='', max_length=150)),
                ('date', models.DateField(blank=True, null=True)),
                ('day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled (Unbooked)'), ('transferred', 'Transferred'), ('completed', 'Completed')], default='booked', max_length=20)),
                ('is_current', models.BooleanField(default=True, help_text="Whether this is the venue's live/active booking.")),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_bookings_created', to=settings.AUTH_USER_MODEL)),
                ('previous_booking', models.ForeignKey(blank=True, help_text='Set automatically when this booking was created by transferring a prior one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_bookings', to='meeting_venues.meetingbooking')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='meeting_venues.meetingvenue')),
            ],
            options={
                'verbose_name': 'Meeting Booking',
                'verbose_name_plural': 'Meeting Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
