# Generated by Django 4.2.30 on 2026-07-30 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting_venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnbookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, default='', max_length=150)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved (Unbooked)'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unbook_requests', to='meeting_venues.meetingbooking')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unbook_requests_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unbook Request',
                'verbose_name_plural': 'Unbook Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
