# Generated by Django 4.2.30 on 2026-07-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCorrectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(db_index=True, max_length=100)),
                ('original_value', models.CharField(max_length=500)),
                ('corrected_value', models.CharField(max_length=500)),
                ('applied_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Import Correction',
                'verbose_name_plural': 'Import Corrections',
                'ordering': ('field', 'original_value'),
                'unique_together': {('field', 'original_value')},
            },
        ),
    ]
