# Generated by Django 4.2.30 on 2026-07-19 00:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import odel_system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecturer_portal', '0001_initial'),
        ('program_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODELCourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.PositiveIntegerField(default=0)),
                ('submitted_to_tt', models.BooleanField(default=False)),
                ('submitted_to_dvc', models.BooleanField(default=False)),
                ('approved_by_dvc', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('reason_for_rejection', models.TextField(blank=True, default='No reason yet', help_text='Provide a reason if rejected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(blank=True, help_text='Assigned lecturer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odel_allocations', to='lecturer_portal.lecturer')),
                ('program_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odel_allocations', to='program_management.programcourse')),
            ],
            options={
                'verbose_name': 'ODEL Course Allocation',
                'verbose_name_plural': 'ODEL Course Allocations',
                'permissions': [('approve_odel_allocation', 'Can approve ODEL course allocation'), ('forward_odel_to_timetable', 'Can forward ODEL to timetable'), ('forward_odel_to_dvc', 'Can forward ODEL to DVC')],
                'unique_together': {('program_course',)},
            },
        ),
        migrations.CreateModel(
            name='ODELTimetableConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date(2026, 8, 18), help_text='Last date for scheduling')),
                ('day_start_time', models.TimeField(default=datetime.time(7, 0), help_text='Daily start time (e.g., 7:00 AM)')),
                ('day_end_time', models.TimeField(default=datetime.time(19, 0), help_text='Daily end time (e.g., 7:00 PM)')),
                ('class_slot_size', models.PositiveIntegerField(default=4, help_text='Number of class slots per day')),
                ('exam_slot_size', models.PositiveIntegerField(default=3, help_text='Number of exam slots per day')),
                ('exam_break_duration', models.PositiveIntegerField(choices=[(30, '30 minutes'), (60, '1 hour'), (90, '1.5 hours'), (120, '2 hours')], default=60, help_text='Break duration between exam slots in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ODEL Timetable Config',
                'verbose_name_plural': 'ODEL Timetable Config',
            },
        ),
        migrations.CreateModel(
            name='PublishedTimetablePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_class_timetable', models.BooleanField(default=False, help_text='True for class timetable, False for exam timetable')),
                ('pdf_file', models.FileField(help_text='The published PDF file', upload_to=odel_system.models.timetable_pdf_upload_path)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number (increments with each publication)')),
                ('is_latest', models.BooleanField(default=True, help_text='Whether this is the latest published version')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Published Timetable PDF',
                'verbose_name_plural': 'Published Timetable PDFs',
                'ordering': ['-published_at', '-version'],
                'permissions': [('publish_timetable', 'Can publish timetables'), ('view_published_timetable', 'Can view published timetables')],
            },
        ),
        migrations.CreateModel(
            name='ODELTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odel_approved', to=settings.AUTH_USER_MODEL)),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='odel_system.odelcourseallocation')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.venue')),
            ],
            options={
                'verbose_name': 'ODEL Timetable',
                'verbose_name_plural': 'ODEL Timetables',
                'ordering': ['date', 'start_time'],
                'permissions': [('approve_odel_timetable', 'Can approve ODEL timetable')],
                'unique_together': {('venue', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='ODELTempTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_timetable_entries', to='odel_system.odelcourseallocation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.venue')),
            ],
            options={
                'verbose_name': 'ODEL Temporary Timetable',
                'verbose_name_plural': 'ODEL Temporary Timetables',
                'ordering': ['date', 'start_time'],
                'unique_together': {('venue', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='ODELExamTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odel_exam_approved', to=settings.AUTH_USER_MODEL)),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_entries', to='odel_system.odelcourseallocation')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.venue')),
            ],
            options={
                'verbose_name': 'ODEL Exam Timetable',
                'verbose_name_plural': 'ODEL Exam Timetables',
                'ordering': ['date', 'start_time'],
                'permissions': [('approve_odel_exam', 'Can approve ODEL exam timetable')],
                'unique_together': {('venue', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='ODELExamTempTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_temp_entries', to='odel_system.odelcourseallocation')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.venue')),
            ],
            options={
                'verbose_name': 'ODEL Temporary Exam Timetable',
                'verbose_name_plural': 'ODEL Temporary Exam Timetables',
                'ordering': ['date', 'start_time'],
                'unique_together': {('venue', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
