# Generated by Django 4.2.30 on 2026-08-01 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odel_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odeltimetableconfig',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 8, 31), help_text='Last date for scheduling'),
        ),
    ]
