# Generated by Django 4.2.30 on 2026-08-03 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odel_system', '0003_alter_odeltimetableconfig_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odeltimetableconfig',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 9, 2), help_text='Last date for scheduling'),
        ),
    ]
