# Generated by Django 4.2.30 on 2026-09-24 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odel_system', '0016_alter_odeltimetableconfig_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odeltimetableconfig',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 10, 24), help_text='Last date for scheduling'),
        ),
    ]
