# Generated by Django 4.2.30 on 2026-07-19 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('sql', 'SQL'), ('bash', 'Bash/Shell'), ('json', 'JSON'), ('yaml', 'YAML'), ('django', 'Django Template'), ('html', 'HTML/CSS'), ('powershell', 'PowerShell'), ('docker', 'Dockerfile')], default='python', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documentation/attachments/%Y/%m/')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fas fa-folder', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('access_level', models.CharField(choices=[('all', 'All Staff'), ('department', 'Department'), ('management', 'Management'), ('admin', 'Administrators')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Documentation Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('short_description', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('page_type', models.CharField(choices=[('guide', '📘 User Guide'), ('tutorial', '🎓 Tutorial'), ('reference', '🔧 Technical Reference'), ('process', '⚙️ Business Process'), ('policy', '📜 Policy'), ('faq', '❓ FAQ'), ('troubleshooting', '🔧 Troubleshooting'), ('api', '🔌 API Documentation'), ('setup', '⚡ Setup Guide'), ('security', '🔒 Security Protocol')], default='guide', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('requires_login', models.BooleanField(default=True)),
                ('access_level', models.CharField(choices=[('all', 'All Staff'), ('department', 'Department'), ('management', 'Management'), ('admin', 'Administrators')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('estimated_read_time', models.IntegerField(default=5, help_text='In minutes')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pages', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_pages', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documentation.documentationcategory')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_pages', to=settings.AUTH_USER_MODEL)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='documentation.documentationpage')),
                ('related_pages', models.ManyToManyField(blank=True, to='documentation.documentationpage')),
            ],
            options={
                'ordering': ['category__order', 'order', 'title'],
                'permissions': [('can_publish_docs', 'Can publish documentation'), ('can_approve_docs', 'Can approve documentation'), ('can_manage_categories', 'Can manage documentation categories')],
            },
        ),
        migrations.CreateModel(
            name='DocumentationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read', models.DateTimeField(auto_now=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('time_spent', models.IntegerField(default=0, help_text='Total time spent in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='documentation.documentationpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_read'],
            },
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='documentation.documentationpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_tags', to='documentation.documentationpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_pages', to='documentation.documentationtag')),
            ],
            options={
                'ordering': ['tag__name'],
            },
        ),
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documentation.documentationpage')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='documentation.documentationpage')),
                ('to_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='documentation.documentationpage')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentationViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='documentation.documentationpage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='documentation.documentationpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('results_count', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='documentation.documentationpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documentation/images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='documentation.documentationpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('publish', 'Published'), ('unpublish', 'Unpublished'), ('archive', 'Archived'), ('delete', 'Deleted')], max_length=20)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('previous_version', models.JSONField(blank=True, null=True)),
                ('new_version', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='documentation.documentationpage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='documentationcategory',
            index=models.Index(fields=['slug', 'is_active'], name='documentati_slug_c4c815_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationcategory',
            index=models.Index(fields=['order'], name='documentati_order_2dfd6b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationcategory',
            index=models.Index(fields=['access_level'], name='documentati_access__68fd0e_idx'),
        ),
        migrations.AddField(
            model_name='documentationattachment',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documentation.documentationpage'),
        ),
        migrations.AddField(
            model_name='codeexample',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_examples', to='documentation.documentationsection'),
        ),
        migrations.AlterUniqueTogether(
            name='userreadingprogress',
            unique_together={('user', 'page')},
        ),
        migrations.AlterUniqueTogether(
            name='userbookmark',
            unique_together={('user', 'page')},
        ),
        migrations.AlterUniqueTogether(
            name='pagetag',
            unique_together={('page', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='internallink',
            unique_together={('from_page', 'to_page')},
        ),
        migrations.AddIndex(
            model_name='documentationviewlog',
            index=models.Index(fields=['page', 'timestamp'], name='documentati_page_id_7584af_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationviewlog',
            index=models.Index(fields=['user', 'timestamp'], name='documentati_user_id_cdf2b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentationsection',
            unique_together={('page', 'slug')},
        ),
        migrations.AddIndex(
            model_name='documentationsearchlog',
            index=models.Index(fields=['query', 'timestamp'], name='documentati_query_95f9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationsearchlog',
            index=models.Index(fields=['user', 'timestamp'], name='documentati_user_id_c21897_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentationrating',
            unique_together={('page', 'user')},
        ),
        migrations.AddIndex(
            model_name='documentationpage',
            index=models.Index(fields=['slug', 'is_published'], name='documentati_slug_f26b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationpage',
            index=models.Index(fields=['category', 'order'], name='documentati_categor_846a79_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationpage',
            index=models.Index(fields=['page_type', 'is_published'], name='documentati_page_ty_2558d8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationpage',
            index=models.Index(fields=['status'], name='documentati_status_7f2b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationpage',
            index=models.Index(fields=['views'], name='documentati_views_90d580_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationpage',
            index=models.Index(fields=['created_at'], name='documentati_created_7857a2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationpage',
            index=models.Index(fields=['updated_at'], name='documentati_updated_c90a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationpage',
            index=models.Index(fields=['access_level'], name='documentati_access__463377_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationchangelog',
            index=models.Index(fields=['page', 'timestamp'], name='documentati_page_id_ff062c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationchangelog',
            index=models.Index(fields=['action', 'timestamp'], name='documentati_action_60beda_idx'),
        ),
    ]
