# Generated by Django 4.2.30 on 2026-07-30 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecturer_portal', '0001_initial'),
        ('program_management', '0001_initial'),
        ('department_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('panel', models.CharField(default='normal', help_text="'normal' (/cod/), 'odel', or 'campuses' — which cod panel this SR was raised on.", max_length=20)),
                ('scope', models.CharField(choices=[('unit', 'This unit only'), ('program', 'This program'), ('program_courses', 'Some courses of this program'), ('lecturer', 'This lecturer')], default='unit', max_length=20)),
                ('course_code', models.CharField(blank=True, default='', max_length=100)),
                ('course_name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(help_text='What should be done for this SR.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('semester', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_reason', models.CharField(blank=True, default='', max_length=200)),
                ('carried_forward_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_forward_to', to='special_requests.specialrequest')),
                ('content_type', models.ForeignKey(blank=True, help_text='Model of the source allocation (CourseAllocation, ODELCourseAllocation, CampusCourseAllocation, ...).', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_requests_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_requests', to='department_management.department')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_requests', to='lecturer_portal.lecturer')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_requests', to='program_management.program')),
            ],
            options={
                'verbose_name': 'Special Request (SR)',
                'verbose_name_plural': 'Special Requests (SR)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='special_req_content_7747a4_idx'), models.Index(fields=['department', 'archived'], name='special_req_departm_623315_idx'), models.Index(fields=['lecturer'], name='special_req_lecture_29e319_idx')],
            },
        ),
    ]
