# Generated by Django 4.2.30 on 2026-07-30 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('special_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialRequestAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('course_code', models.CharField(blank=True, default='', max_length=100)),
                ('course_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('special_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_links', to='special_requests.specialrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='special_req_content_b0f9ab_idx')],
                'unique_together': {('special_request', 'content_type', 'object_id')},
            },
        ),
    ]
