# Generated by Django 4.2.30 on 2026-07-19 00:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_allocation', '0001_initial'),
        ('room_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedulerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Start date of the exam period')),
                ('start_time', models.TimeField(default=datetime.time(8, 0), help_text='Earliest exam start time')),
                ('end_time', models.TimeField(default=datetime.time(17, 0), help_text='Latest exam end time')),
                ('slot_size', models.PositiveIntegerField(default=2, help_text='Duration of one exam session (in hours)')),
                ('excluded_days', models.TextField(blank=True, default='', help_text='Comma-separated dates (YYYY-MM-DD) to skip. Weekends are populated automatically on save; you may add public holidays or any other dates here.')),
                ('max_exam_days', models.PositiveIntegerField(default=14, help_text='Number of valid exam days required. Weekends and excluded dates are NOT counted – the scheduler will keep walking forward until this many working days are found.')),
                ('spacing_ratio', models.FloatField(default=0.7, help_text='Allowed fill ratio for venue capacity (e.g. 0.7 = use up to 70 % of capacity)')),
            ],
            options={
                'verbose_name': 'Exam Scheduler Config',
                'verbose_name_plural': 'Exam Scheduler Configs',
            },
        ),
        migrations.CreateModel(
            name='ExamTempTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_temp_timetable_entries', to='course_allocation.courseallocation')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.venue')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_timetable_entries', to='course_allocation.courseallocation')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.venue')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'permissions': [('approve_timetable', 'Can approve timetable')],
            },
        ),
        migrations.CreateModel(
            name='LabSchedulerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(7, 0))),
                ('end_time', models.TimeField(default=datetime.time(19, 0))),
                ('slot_size', models.PositiveIntegerField(default=2, help_text='Slot size in hours')),
            ],
            options={
                'verbose_name': 'Scheduler Configuration',
                'verbose_name_plural': 'Scheduler Configuration',
            },
        ),
        migrations.CreateModel(
            name='SchedulerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='07:00')),
                ('end_time', models.TimeField(default='19:00')),
                ('slot_size', models.PositiveIntegerField(default=3, help_text='Slot size in hours')),
                ('enable_evening_classes', models.BooleanField(default=False, help_text='When enabled, courses marked as Evening/Weekend (is_evening_weekend=True) are scheduled into evening slots on weekdays. Regular courses are never placed here.')),
                ('evening_start_time', models.TimeField(default='19:00', help_text='Start of the evening session (default 19:00 / 7 PM).')),
                ('evening_end_time', models.TimeField(default='21:00', help_text='End of the evening session (default 21:00 / 9 PM).')),
                ('evening_slot_count', models.PositiveIntegerField(default=1, help_text='Maximum number of evening slots per weekday. Default is 1 (a single 7–9 PM block).')),
                ('enable_weekend_classes', models.BooleanField(default=False, help_text='When enabled, courses marked as Evening/Weekend (is_evening_weekend=True) that could not fit in evening slots are placed on Saturday. Regular courses are never placed here.')),
                ('weekend_start_time', models.TimeField(default='09:00', help_text='Start time for weekend sessions (default 09:00 / 9 AM).')),
                ('weekend_end_time', models.TimeField(default='17:00', help_text='End time for weekend sessions (default 17:00 / 5 PM).')),
                ('weekend_slot_size', models.PositiveIntegerField(default=3, help_text='Slot duration in hours for weekend sessions (default 3 hrs).')),
            ],
            options={
                'verbose_name': 'Scheduler Configuration',
                'verbose_name_plural': 'Scheduler Configuration',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='course_allocation.courseallocation')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.venue')),
            ],
            options={
                'permissions': [('approve_timetable', 'Can approve timetable')],
            },
        ),
        migrations.CreateModel(
            name='TempTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_timetable_entries', to='course_allocation.courseallocation')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.venue')),
            ],
        ),
        migrations.CreateModel(
            name='SharedVenueExamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('day', models.CharField(help_text='Day of the exam (e.g., Monday)', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_students', models.PositiveIntegerField(default=0, help_text='Total number of students across all shared courses')),
                ('published', models.BooleanField(default=False, help_text='Has this shared group been published/approved?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_allocations', models.ManyToManyField(help_text='Courses sharing this venue at the same time', related_name='shared_exam_venues', to='course_allocation.courseallocation')),
                ('exam_temp_timetable_entry', models.ForeignKey(blank=True, help_text='Draft ExamTempTimetable entry for this shared group (used when published=False)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_venue_groups_temp', to='timetable.examtemptimetable')),
                ('exam_timetable_entry', models.ForeignKey(blank=True, help_text='Published ExamTimetable entry for this shared group (used when published=True)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_venue_groups', to='timetable.examtimetable')),
                ('venue', models.ForeignKey(help_text='Venue being shared for this exam session', on_delete=django.db.models.deletion.CASCADE, related_name='shared_exam_groups', to='room_management.venue')),
            ],
            options={
                'verbose_name': 'Shared Venue Exam Group',
                'verbose_name_plural': 'Shared Venue Exam Groups',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MergedCourseGroupTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_code', models.CharField(blank=True, help_text='Normalized base course code (e.g., COSC312)', max_length=50)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('date', models.CharField(blank=True, default='check in timetable', max_length=100)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False, help_text='Has this merged group been published/approved?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_course', models.ForeignKey(help_text='Representative base course for this merged timetable group', on_delete=django.db.models.deletion.CASCADE, related_name='auto_merged_as_base', to='course_allocation.courseallocation')),
                ('merged_courses', models.ManyToManyField(help_text='All course allocations included in this merged timetable slot', related_name='auto_merged_groups', to='course_allocation.courseallocation')),
                ('temp_timetable_entry', models.ForeignKey(blank=True, help_text='Draft TempTimetable entry for the base course (used when published=False)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_timetable_groups_temp', to='timetable.temptimetable')),
                ('timetable_entry', models.ForeignKey(blank=True, help_text='Published Timetable entry for the base course (used when published=True)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_timetable_groups', to='timetable.timetable')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room_management.venue')),
            ],
            options={
                'db_table': 'timetable_automergedexamgroup',
            },
        ),
        migrations.CreateModel(
            name='MergedCourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_code', models.CharField(blank=True, help_text='Normalized base code', max_length=50)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False, help_text='Has this merged group been published/approved?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_course', models.ForeignKey(help_text='Representative course allocation (first code)', on_delete=django.db.models.deletion.CASCADE, related_name='merged_as_base', to='course_allocation.courseallocation')),
                ('exam_temp_timetable_entry', models.ForeignKey(blank=True, help_text='Draft ExamTempTimetable entry for the base course (used when published=False)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_course_groups_temp', to='timetable.examtemptimetable')),
                ('exam_timetable_entry', models.ForeignKey(blank=True, help_text='Published ExamTimetable entry for the base course (used when published=True)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_course_groups', to='timetable.examtimetable')),
                ('merged_courses', models.ManyToManyField(help_text='All course allocations included in this merged exam', related_name='merged_groups', to='course_allocation.courseallocation')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room_management.venue')),
            ],
        ),
        migrations.CreateModel(
            name='LabTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=16)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_timetables', to='course_allocation.laballocation')),
                ('lab_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_timetable_entries', to='room_management.labvenue')),
            ],
        ),
        migrations.CreateModel(
            name='LabExamTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('day', models.CharField(max_length=16)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_exam_timetables', to='course_allocation.laballocation')),
                ('lab_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_exam_timetable_entries', to='room_management.labvenue')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimetableArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable_type', models.CharField(choices=[('MAIN', 'Main Timetable'), ('EXAM', 'Exam Timetable')], max_length=10)),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester')], max_length=2)),
                ('academic_year', models.CharField(help_text='e.g. 2024/2025', max_length=15)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField()),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-archived_at'],
                'unique_together': {('semester', 'academic_year', 'timetable_type')},
            },
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['day'], name='timetable_t_day_d328bc_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['day', 'start_time', 'end_time'], name='timetable_t_day_e8c62f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temptimetable',
            unique_together={('venue', 'day', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='sharedvenueexamgroup',
            unique_together={('venue', 'date', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='labtimetable',
            unique_together={('lab_venue', 'day', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='labexamtimetable',
            unique_together={('lab_venue', 'date', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='examtemptimetable',
            unique_together={('venue', 'date', 'start_time', 'end_time')},
        ),
    ]
