# Generated by Django 4.2.30 on 2026-08-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_allocation', '0013_combinedcoursegroup_origin_department_and_more'),
        ('room_management', '0003_alter_venueblock_id'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='temptimetable',
            unique_together={('course_allocation', 'venue', 'day', 'start_time', 'end_time')},
        ),
    ]
