# Generated by Django 4.2.30 on 2026-08-24 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0003_alter_venueblock_id'),
        ('lecturer_portal', '0001_initial'),
        ('timetable', '0002_alter_temptimetable_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerTimePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_preferences', to='lecturer_portal.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerVenuePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_preferences', to='lecturer_portal.lecturer')),
                ('venues', models.ManyToManyField(help_text='One or more venues this lecturer prefers to be scheduled in.', related_name='lecturer_preferences', to='room_management.venue')),
            ],
            options={
                'verbose_name': 'Lecturer Venue Preference',
                'verbose_name_plural': 'Lecturer Venue Preferences',
                'ordering': ['lecturer__name'],
            },
        ),
        migrations.CreateModel(
            name='LecturerBlockedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField(blank=True, help_text='Leave blank together with End Time to block the entire day.', null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='lecturer_portal.lecturer')),
            ],
            options={
                'verbose_name': 'Lecturer Blocked Slot',
                'verbose_name_plural': 'Lecturer Blocked Slots',
                'ordering': ['lecturer__name', 'day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='LecturerTimePreferenceSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField(blank=True, help_text='Null = whole day', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Null = whole day', null=True)),
                ('is_whole_day', models.BooleanField(default=False)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.lecturertimepreference')),
            ],
            options={
                'ordering': ['day', 'start_time'],
                'unique_together': {('preference', 'day', 'start_time', 'end_time')},
            },
        ),
    ]
