# Generated by Django 4.2.30 on 2026-09-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_analysisaccessshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisaccessshare',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
