# Generated by Django 4.2.30 on 2026-09-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_timetableissue'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='timetableissue',
            new_name='timetable_t_timetab_798f8e_idx',
            old_name='tt_issue_entry_idx',
        ),
        migrations.AlterField(
            model_name='timetableissue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
