# Generated by Django 4.2.30 on 2026-07-19 00:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('reg_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('username', models.CharField(blank=True, max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('password', models.CharField(default='123', max_length=128)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_reps', to='program_management.program')),
            ],
        ),
        migrations.CreateModel(
            name='MinimalTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('class_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minimal_timetable', to='classreps.classrep')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRepNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='classreps.classrep')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
