# Generated by Django 4.2.30 on 2026-07-19 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program_management', '0001_initial'),
        ('department_management', '0001_initial'),
        ('lecturer_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=200)),
                ('number_of_students', models.PositiveIntegerField(default=0)),
                ('approved_by_dvc', models.BooleanField(default=False)),
                ('rejected_by_dvc', models.BooleanField(default=False)),
                ('reason_for_disapproval', models.TextField(blank=True, default='No reason yet', help_text='Provide a reason if the DVC rejects this course.')),
                ('submitted_to_tt', models.BooleanField(default=False)),
                ('intake', models.CharField(choices=[('normal', 'Normal'), ('special', 'Special')], db_index=True, default='normal', help_text='Normal = standard cohort. Special = shifted-semester cohort within the same programme year.', max_length=10)),
                ('is_elective', models.BooleanField(default=False, help_text='Mark as a Selection / Elective course. Can be added to a SelectionGroup so students choose one from the group.')),
                ('is_evening_weekend', models.BooleanField(default=False, help_text='Mark as an Evening / Weekend class. Displayed separately below the regular allocations.')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='department_management.department')),
                ('lecturer', models.ForeignKey(blank=True, help_text='Assigned lecturer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_allocations', to='lecturer_portal.lecturer')),
                ('origin_department', models.ForeignKey(blank=True, help_text='Original department offering this course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_allocations', to='department_management.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='program_management.program')),
                ('program_course', models.ForeignKey(help_text='The ProgramCourse (curriculum entry) this allocation is derived from. Required — every allocation must belong to a curriculum course. Deleting the ProgramCourse will cascade-delete this allocation.', on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to='program_management.programcourse')),
            ],
            options={
                'permissions': [('approve_course_allocation', 'Can approve course allocation (DVC only)'), ('forward_course_allocation', 'Can forward course allocation to timetable (COD only)')],
            },
        ),
        migrations.CreateModel(
            name='SubmissionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_submission_to_dvc', models.BooleanField(default=True)),
                ('allow_submission_to_tt', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_control', to='department_management.department')),
            ],
            options={
                'verbose_name': 'Submission Control',
                'verbose_name_plural': 'Submission Controls',
            },
        ),
        migrations.CreateModel(
            name='SelectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name, e.g. 'Year 3 Semester 1 Electives – Group A'.", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, help_text='Only elective CourseAllocations may be added here.', limit_choices_to={'is_elective': True}, related_name='selection_groups', to='course_allocation.courseallocation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_selection_groups', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_groups', to='department_management.department')),
                ('program', models.ForeignKey(blank=True, help_text='Optional: restrict this group to a specific program.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection_groups', to='program_management.program')),
            ],
            options={
                'verbose_name': 'Selection Group',
                'verbose_name_plural': 'Selection Groups',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.PositiveIntegerField(default=0)),
                ('is_workshop_course', models.BooleanField(default=False, help_text='Mark this allocation as a Workshop course. Workshop sessions are scheduled into LabTimetable just like regular lab sessions but are displayed/filtered separately.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('additional_courses', models.ManyToManyField(blank=True, help_text='Extra course codes that share this lab allocation.', related_name='additional_lab_allocations', to='program_management.programcourse')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecturer_portal.lecturer')),
                ('program_course', models.ForeignKey(help_text='Primary / first course for this allocation.', on_delete=django.db.models.deletion.CASCADE, related_name='lab_allocations', to='program_management.programcourse')),
                ('venues', models.ManyToManyField(help_text='Candidate venues; the autoscheduler picks one per session.', related_name='lab_allocations', to='room_management.labvenue')),
            ],
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='selection_group',
            field=models.ForeignKey(blank=True, help_text='Optional. The primary SelectionGroup this elective allocation belongs to. Students in the program must choose exactly one course from this group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_allocations', to='course_allocation.selectiongroup'),
        ),
        migrations.CreateModel(
            name='CombinedCourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(help_text="Unique identifier for this combined group, e.g. 'COSC201_COMBINED'", max_length=50, unique=True)),
                ('base_course_code', models.CharField(help_text="Base course code without group suffix, e.g. 'COSC 201'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocations', models.ManyToManyField(help_text='All course allocations that are combined together', related_name='combined_groups', to='course_allocation.courseallocation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_combined_groups', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='The origin department that created this combined group', on_delete=django.db.models.deletion.CASCADE, related_name='combined_groups', to='department_management.department')),
                ('lecturer', models.ForeignKey(blank=True, help_text='The lecturer who teaches this combined group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combined_groups', to='lecturer_portal.lecturer')),
                ('primary_allocation', models.ForeignKey(blank=True, help_text='The main allocation that represents this combined group for scheduling', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_primary_of_combined_group', to='course_allocation.courseallocation')),
            ],
            options={
                'verbose_name': 'Combined Course Group',
                'verbose_name_plural': 'Combined Course Groups',
                'ordering': ['base_course_code', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BaseSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_base_selections', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Department that owns this base selection list.', on_delete=django.db.models.deletion.CASCADE, related_name='base_selections', to='department_management.department')),
                ('program_course', models.ForeignKey(help_text='ProgramCourse that represents this base selection.', on_delete=django.db.models.deletion.CASCADE, related_name='base_selections', to='program_management.programcourse')),
            ],
            options={
                'verbose_name': 'Base Selection Course',
                'verbose_name_plural': 'Base Selection Courses',
            },
        ),
        migrations.CreateModel(
            name='ArchivedCourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='Semester identifier (e.g. 1, 2, 3 or 2025S1)', max_length=32)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('number_of_students', models.PositiveIntegerField(default=0)),
                ('approved_by_dvc', models.BooleanField(default=False)),
                ('rejected_by_dvc', models.BooleanField(default=False)),
                ('reason_for_disapproval', models.TextField(blank=True, default='No reason yet')),
                ('submitted_to_tt', models.BooleanField(default=False)),
                ('intake', models.CharField(choices=[('normal', 'Normal'), ('special', 'Special')], default='normal', max_length=10)),
                ('combination_name', models.CharField(blank=True, default='', max_length=200)),
                ('selection_group_name', models.CharField(blank=True, default='', max_length=200)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_by_user', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_allocations', to='department_management.department')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecturer_portal.lecturer')),
                ('origin_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_origin_allocations', to='department_management.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program_management.program')),
            ],
            options={
                'verbose_name': 'Archived Course Allocation',
                'verbose_name_plural': 'Archived Course Allocations',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_load_per_semester', models.PositiveSmallIntegerField(default=6, help_text='Default max CourseAllocations a lecturer may carry PER SEMESTER (explicitly per-semester, not per-year/global). Individual lecturers can still override this via Lecturer.max_load_override for seniority-based exceptions.')),
                ('max_load_enabled', models.BooleanField(default=True, help_text='If False, the load cap is disabled entirely for this scope — lecturers may be allocated an unlimited number of courses.')),
                ('split_threshold', models.PositiveIntegerField(default=200, help_text='Student count above which a course is auto-split into groups.')),
                ('split_size', models.PositiveIntegerField(default=100, help_text='Target number of students per split group.')),
                ('splitting_enabled', models.BooleanField(default=True, help_text='If False, courses in this scope are never auto-split, regardless of student count.')),
                ('pg_designations', models.CharField(default='Dr,Prof', help_text='Comma-separated Lecturer.designation codes considered qualified to teach postgraduate-level courses.', max_length=200)),
                ('allowed_semesters', models.CharField(default='1,2', help_text="Comma-separated valid semester numbers, e.g. '1,2,3' for a trimester system. The autoallocator validates against this instead of a hardcoded (1, 2) tuple.", max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(blank=True, help_text='Leave blank for the GLOBAL default config (exactly one such row).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocation_config', to='department_management.department')),
            ],
            options={
                'verbose_name': 'Allocation Config',
                'verbose_name_plural': 'Allocation Configs',
            },
        ),
        migrations.CreateModel(
            name='ProgramEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=1, help_text='Year of study (1-6)')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1)),
                ('number_of_students', models.PositiveIntegerField(default=0)),
                ('academic_year', models.CharField(blank=True, default='', help_text='Academic year label e.g. 2024/2025', max_length=20)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='program_management.program')),
            ],
            options={
                'verbose_name': 'Program Enrollment',
                'verbose_name_plural': 'Program Enrollments',
                'unique_together': {('program', 'year', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='LecturerCourseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, help_text='Courses this lecturer is qualified to teach.', related_name='lecturer_mappings', to='program_management.programcourse')),
                ('department', models.ForeignKey(blank=True, help_text='Department context for this mapping.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_course_mappings', to='department_management.department')),
                ('lecturer', models.ForeignKey(help_text='Lecturer who can teach these courses.', on_delete=django.db.models.deletion.CASCADE, related_name='course_mappings', to='lecturer_portal.lecturer')),
            ],
            options={
                'verbose_name': 'Lecturer Course Mapping',
                'verbose_name_plural': 'Lecturer Course Mappings',
                'unique_together': {('lecturer', 'department')},
            },
        ),
        migrations.CreateModel(
            name='DVCActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alloc_type', models.CharField(choices=[('standard', 'Standard'), ('campus', 'Campus'), ('odel', 'ODEL')], default='standard', max_length=10)),
                ('action', models.CharField(choices=[('submit', 'COD Submitted'), ('approve', 'DVC Approved'), ('reject', 'DVC Rejected')], max_length=10)),
                ('course_code', models.CharField(blank=True, default='', max_length=100)),
                ('course_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reported', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dvc_action_logs', to='department_management.department')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvc_action_logs', to='lecturer_portal.lecturer')),
            ],
            options={
                'verbose_name': 'DVC Action Log',
                'verbose_name_plural': 'DVC Action Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['department', 'reported'], name='course_allo_departm_5572b0_idx'), models.Index(fields=['created_at'], name='course_allo_created_0f0fcf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='courseallocation',
            index=models.Index(fields=['course_code'], name='course_allo_course__aee0bd_idx'),
        ),
        migrations.AddIndex(
            model_name='courseallocation',
            index=models.Index(fields=['program', 'course_code'], name='course_allo_program_0d9fe3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='baseselection',
            unique_together={('program_course', 'department')},
        ),
    ]
