# Generated by Django 4.2.30 on 2026-08-02 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0004_normalize_unit_type_typos'),
        ('department_management', '0001_initial'),
        ('lecturer_portal', '0001_initial'),
        ('course_allocation', '0003_archivedcourseallocation_program_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationconfig',
            name='split_size',
        ),
        migrations.AddField(
            model_name='allocationconfig',
            name='split_extend_by',
            field=models.PositiveIntegerField(default=0, help_text='How much the threshold can be exceeded before triggering a split. e.g., threshold=200, extend_by=20 → groups up to 220 students are allowed. A 220-student course → 1 group (220 ≤ 220). A 221-student course → 2 groups (ceil(221/200) = 2 → 110 + 111).'),
        ),
        migrations.AlterField(
            model_name='academicyeartracker',
            name='current_year',
            field=models.PositiveIntegerField(help_text="Calendar year that currently counts as 'Year 1' of study."),
        ),
        migrations.AlterField(
            model_name='allocationconfig',
            name='allowed_semesters',
            field=models.CharField(default='1,2', help_text='Comma-separated valid semester numbers.', max_length=100),
        ),
        migrations.AlterField(
            model_name='allocationconfig',
            name='max_load_enabled',
            field=models.BooleanField(default=True, help_text='If False, the load cap is disabled entirely.'),
        ),
        migrations.AlterField(
            model_name='allocationconfig',
            name='max_load_per_semester',
            field=models.PositiveSmallIntegerField(default=6, help_text='Default max CourseAllocations a lecturer may carry PER SEMESTER.'),
        ),
        migrations.AlterField(
            model_name='allocationconfig',
            name='split_threshold',
            field=models.PositiveIntegerField(default=200, help_text='Maximum number of students allowed per group (hard limit). If students exceed threshold + extend_by, the course is split into the minimum number of groups where no group exceeds threshold.'),
        ),
        migrations.AlterField(
            model_name='allocationconfig',
            name='splitting_enabled',
            field=models.BooleanField(default=True, help_text='If False, courses are never auto-split.'),
        ),
        migrations.AlterField(
            model_name='archivedcourseallocation',
            name='program_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_course_allocations', to='program_management.programcourse'),
        ),
        migrations.AlterField(
            model_name='archivedcourseallocation',
            name='semester',
            field=models.CharField(help_text='Semester identifier', max_length=32),
        ),
        migrations.AlterField(
            model_name='combinedcoursegroup',
            name='allocations',
            field=models.ManyToManyField(related_name='combined_groups', to='course_allocation.courseallocation'),
        ),
        migrations.AlterField(
            model_name='combinedcoursegroup',
            name='base_course_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='combinedcoursegroup',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_groups', to='department_management.department'),
        ),
        migrations.AlterField(
            model_name='combinedcoursegroup',
            name='group_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='combinedcoursegroup',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combined_groups', to='lecturer_portal.lecturer'),
        ),
        migrations.AlterField(
            model_name='combinedcoursegroup',
            name='primary_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_primary_of_combined_group', to='course_allocation.courseallocation'),
        ),
        migrations.AlterField(
            model_name='laballocation',
            name='is_workshop_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='programenrollment',
            name='entry_year',
            field=models.PositiveIntegerField(help_text='Calendar year this cohort was admitted.'),
        ),
    ]
