# Generated by Django 4.2.30 on 2026-08-03 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0004_normalize_unit_type_typos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department_management', '0001_initial'),
        ('course_allocation', '0004_remove_allocationconfig_split_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name, e.g. 'Year 3 Semester 1 Specialization'.", max_length=200)),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Optional: the program year this specialization applies to (e.g. Year 3).', null=True)),
                ('semester', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2')], help_text='Optional: the semester this specialization applies to.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_specialization_categories', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization_categories', to='department_management.department')),
                ('program', models.ForeignKey(help_text='The program these specialization stems belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='specialization_categories', to='program_management.program')),
            ],
            options={
                'verbose_name': 'Specialization Category',
                'verbose_name_plural': 'Specialization Categories',
                'ordering': ['department', 'program', 'year', 'semester', 'name'],
                'unique_together': {('program', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SpecializationStem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Artificial Intelligence', 'Cybersecurity', 'Networking'.", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stems', to='course_allocation.specializationcategory')),
                ('courses', models.ManyToManyField(blank=True, help_text='The set of courses a student takes if they choose this stem.', related_name='specialization_stems', to='course_allocation.courseallocation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_specialization_stems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Specialization Stem',
                'verbose_name_plural': 'Specialization Stems',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='specialization_stem',
            field=models.ForeignKey(blank=True, help_text="Optional. The SpecializationStem (e.g. 'Artificial Intelligence', 'Cybersecurity') this course belongs to. Students choose exactly one stem out of the SpecializationCategory and take EVERY course inside that stem. Unlike a SelectionGroup, courses inside the SAME stem must still be checked for clashes against each other; only courses that belong to DIFFERENT stems of the same category are exempt from clashing with one another.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_allocations', to='course_allocation.specializationstem'),
        ),
    ]
