# Generated by Django 4.2.30 on 2026-08-04 06:06
# Manually reordered: fields must be added before any index that references
# them. The autodetector originally emitted AddIndex(special_intake_group)
# BEFORE the AddField that creates that column, which fails on every backend
# ("unknown column") the moment it's reached. Order below is dependency-safe:
#   1. Create the new model (no FKs yet, avoids circular dependency)
#   2. Add both new FK fields
#   3. Add indexes (both referenced columns now exist)
#   4. Add the unique_together constraint

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0004_normalize_unit_type_typos'),
        ('course_allocation', '0006_alter_archivedcourseallocation_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialIntakeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='Year of study (1-6) this special intake cohort is in.')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], help_text='Semester this special intake cohort is in.')),
                ('entry_year', models.PositiveIntegerField(help_text='Calendar year this special intake cohort was admitted.')),
                ('number_of_students', models.PositiveIntegerField(default=0, help_text='Total number of students in this special intake cohort.')),
                ('academic_year', models.CharField(blank=True, help_text="e.g. '2024/2025' - auto-generated from entry_year.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Special Intake Group',
                'verbose_name_plural': 'Special Intake Groups',
                'ordering': ['program', '-entry_year', 'year', 'semester'],
            },
        ),
        migrations.AddField(
            model_name='specialintakegroup',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_intake_groups', to='program_management.program'),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='special_intake_group',
            field=models.ForeignKey(blank=True, help_text='If this is a special intake allocation, link to the group it belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_allocations', to='course_allocation.specialintakegroup'),
        ),
        migrations.AddIndex(
            model_name='courseallocation',
            index=models.Index(fields=['intake'], name='course_allo_intake_c8dbfe_idx'),
        ),
        migrations.AddIndex(
            model_name='courseallocation',
            index=models.Index(fields=['special_intake_group'], name='course_allo_special_445e2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='specialintakegroup',
            unique_together={('program', 'year', 'semester', 'entry_year')},
        ),
    ]
