# Generated by Django 4.2.30 on 2026-08-10 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program_management', '0006_rename_program_man_status_e5b1a1_idx_program_man_status_31190c_idx_and_more'),
        ('course_allocation', '0008_specialintakegroup_semester3'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='Year of study (1-6) this group belongs to.')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3')], help_text='Semester this group belongs to.')),
                ('intake', models.CharField(choices=[('normal', 'Normal'), ('special', 'Special')], default='normal', help_text='Normal or Special intake.', max_length=10)),
                ('name', models.CharField(help_text="Group name, e.g. 'Group A', 'Group B'.", max_length=100)),
                ('letter', models.CharField(help_text="Group letter, e.g. 'A', 'B', 'C'.", max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Group',
                'verbose_name_plural': 'Student Groups',
                'ordering': ['program', 'year', 'semester', 'intake', 'letter'],
            },
        ),
        migrations.AddField(
            model_name='archivedcourseallocation',
            name='student_group_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='program',
            field=models.ForeignKey(help_text='The program this group belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='program_management.program'),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='student_group',
            field=models.ForeignKey(blank=True, help_text='The student group this allocation belongs to. If null, this course is shared across all groups in the program/year (typically electives or specialization-stem courses).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_allocations', to='course_allocation.studentgroup'),
        ),
        migrations.AddIndex(
            model_name='courseallocation',
            index=models.Index(fields=['student_group'], name='course_allo_student_efe7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentgroup',
            index=models.Index(fields=['program', 'year', 'semester', 'intake'], name='course_allo_program_d3b7e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentgroup',
            unique_together={('program', 'year', 'semester', 'intake', 'letter')},
        ),
    ]
