# Generated by Django 4.2.30 on 2026-08-13 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program_management', '0006_rename_program_man_status_e5b1a1_idx_program_man_status_31190c_idx_and_more'),
        ('department_management', '0001_initial'),
        ('lecturer_portal', '0001_initial'),
        ('course_allocation', '0010_alter_studentgroup_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCombinationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_course_code', models.CharField(help_text="Normalized base course code shared by every allocation in this combination, e.g. 'COSC 101'.", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_combination_templates', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_combination_templates', to='department_management.department')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_combination_templates', to='lecturer_portal.lecturer')),
            ],
            options={
                'verbose_name': 'Course Combination Template',
                'verbose_name_plural': 'Course Combination Templates',
                'ordering': ['department', 'base_course_code'],
                'unique_together': {('department', 'base_course_code')},
            },
        ),
        migrations.CreateModel(
            name='GroupingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='Year of study (1-6) this template applies to.')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3')])),
                ('intake', models.CharField(choices=[('normal', 'Normal'), ('special', 'Special')], default='normal', max_length=10)),
                ('scope', models.CharField(choices=[('all', 'All compulsory courses'), ('selected', 'Selected courses only')], default='all', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grouping_templates', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouping_templates', to='program_management.program')),
            ],
            options={
                'verbose_name': 'Grouping Template',
                'verbose_name_plural': 'Grouping Templates',
                'ordering': ['program', 'year', 'semester', 'intake'],
                'unique_together': {('program', 'year', 'semester', 'intake')},
            },
        ),
        migrations.CreateModel(
            name='GroupingTemplateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=4)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='course_allocation.groupingtemplate')),
            ],
            options={
                'verbose_name': 'Grouping Template Group',
                'verbose_name_plural': 'Grouping Template Groups',
                'ordering': ['letter'],
                'unique_together': {('template', 'letter')},
            },
        ),
        migrations.CreateModel(
            name='GroupingTemplateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_course_code', models.CharField(max_length=100)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_codes', to='course_allocation.groupingtemplate')),
            ],
            options={
                'verbose_name': 'Grouping Template Course',
                'verbose_name_plural': 'Grouping Template Courses',
                'unique_together': {('template', 'base_course_code')},
            },
        ),
        migrations.CreateModel(
            name='CourseCombinationTemplateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_combination_template_links', to='program_management.program')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='course_allocation.coursecombinationtemplate')),
            ],
            options={
                'verbose_name': 'Course Combination Template Program',
                'verbose_name_plural': 'Course Combination Template Programs',
                'unique_together': {('template', 'program')},
            },
        ),
    ]
