# Generated by Django 4.2.30 on 2026-08-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_allocation', '0011_coursecombinationtemplate_groupingtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectiongroup',
            name='restricted_to_groups',
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Optional: restrict this elective choice to specific Student "
                    "Groups (e.g. only Group C may choose from this pool). Leave "
                    "empty to keep it shared/open to every group in the "
                    "program/year/semester, same as before this field existed."
                ),
                related_name='available_selection_groups',
                to='course_allocation.studentgroup',
            ),
        ),
        migrations.AddField(
            model_name='specializationstem',
            name='restricted_to_groups',
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Optional: restrict this stem to specific Student Groups (e.g. "
                    "only Group A and Group B may choose this stem, while Group C "
                    "may not). Leave empty to keep it shared/open to every group in "
                    "the program/year/semester, same as before this field existed."
                ),
                related_name='available_stems',
                to='course_allocation.studentgroup',
            ),
        ),
    ]
