# Generated by Django 4.2.30 on 2026-08-14 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _backfill_origin_department(apps, schema_editor):
    """
    Every CombinedCourseGroup that already exists was created by the
    department that currently holds it (there was no submit/split flow
    before this migration), so origin_department == department for all
    of them at the moment this field is introduced.
    """
    CombinedCourseGroup = apps.get_model("course_allocation", "CombinedCourseGroup")
    CombinedCourseGroup.objects.filter(origin_department__isnull=True).update(
        origin_department=models.F("department")
    )


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("department_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course_allocation", "0012_selectiongroup_restricted_to_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="combinedcoursegroup",
            name="origin_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                help_text=(
                    "Servicing/originating department — the COD who first "
                    "combined this group. Kept fixed even after the group is "
                    "submitted to another department for lecturer allocation."
                ),
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="origin_combined_groups",
                to="department_management.department",
            ),
        ),
        migrations.AlterField(
            model_name="combinedcoursegroup",
            name="department",
            field=models.ForeignKey(
                help_text=(
                    "Allocating department — currently responsible for "
                    "assigning a lecturer to this combined group."
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="combined_groups",
                to="department_management.department",
            ),
        ),
        migrations.AddField(
            model_name="combinedcoursegroup",
            name="split_from_group_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                help_text=(
                    "If this group was produced by splitting a submitted "
                    "combined group, the group_code of that parent (the "
                    "parent row itself is deleted once split, so this is a "
                    "historical snapshot, not a live FK)."
                ),
            ),
        ),
        migrations.AddField(
            model_name="combinedcoursegroup",
            name="split_from_group_id",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                help_text=(
                    "Historical id of the parent group that was split to "
                    "produce this one (not a live FK — the parent row no "
                    "longer exists)."
                ),
            ),
        ),
        migrations.RunPython(_backfill_origin_department, _noop_reverse),
    ]
