# Generated by hand on 2026-09-13 (bulk multi-course group creation feature)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_allocation', '0017_laballocation_allocation_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseallocation',
            name='additional_student_groups',
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Extra StudentGroups this allocation (e.g. one lettered "
                    "common-course group, EDFO 111-C) is ALSO offered to, on "
                    "top of the single `student_group` above. Added for the "
                    "bulk multi-course group creation flow, where one "
                    "lettered group can be mapped to more than one student "
                    "group at once. `student_group` stays the 'primary' "
                    "group (kept for backward compatibility with every "
                    "existing single-group query/filter); this field is "
                    "purely additive — a group with only `student_group` "
                    "set and an empty `additional_student_groups` behaves "
                    "exactly as before. Use the `all_mapped_student_groups` "
                    "property to read the full combined set."
                ),
                related_name='additional_course_allocations',
                to='course_allocation.studentgroup',
            ),
        ),
    ]
