# Generated by Django 4.2.30 on 2026-09-17 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0007_alter_programcourse_semester'),
        ('course_allocation', '0018_courseallocation_additional_student_groups'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='allocationset',
            new_name='course_allo_departm_2b3f10_idx',
            old_name='course_allo_departm_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='allocationset',
            new_name='course_allo_departm_0b2deb_idx',
            old_name='course_allo_departm_d4e5f6_idx',
        ),
        migrations.AlterField(
            model_name='allocationset',
            name='academic_year',
            field=models.CharField(blank=True, default='', help_text='e.g. 2026/2027', max_length=20),
        ),
        migrations.AlterField(
            model_name='allocationset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='allocationset',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Hidden from the active picker but never deleted.'),
        ),
        migrations.AlterField(
            model_name='allocationset',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='True only for the auto-created set that absorbed pre-migration data. Never set by users.'),
        ),
        migrations.AlterField(
            model_name='allocationset',
            name='is_special',
            field=models.BooleanField(default=False, help_text='Special allocation (shifted-semester / special-intake cohort). Independent of allocation_type.'),
        ),
        migrations.AlterField(
            model_name='allocationset',
            name='name',
            field=models.CharField(help_text="e.g. 'Semester 1 2026/2027', 'Semester 1 + selected Sem 2 units', 'Special Intake Sept 2026'.", max_length=150),
        ),
        migrations.AlterField(
            model_name='allocationsetcomponentcourse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='allocationsetsemestercomponent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='allocationsetsemestercomponent',
            name='programs',
            field=models.ManyToManyField(blank=True, help_text='Used only when scope=SELECTED.', related_name='allocation_set_components', to='program_management.program'),
        ),
        migrations.AlterField(
            model_name='allocationsetsemestercomponent',
            name='semester_number',
            field=models.PositiveSmallIntegerField(help_text='1, 2, 3, ... — no upper limit assumed.'),
        ),
        migrations.AlterField(
            model_name='archivedcourseallocation',
            name='allocation_set',
            field=models.ForeignKey(blank=True, help_text='Which concurrent AllocationSet this archive came from. Without this, archives from different concurrent sets that happen to share the same semester label got merged together on restore/delete — the same class of cross-set bleed already fixed for live CourseAllocation rows. Null only for archives created before this field existed; those are treated as legacy/unscoped and shown regardless of which set is active.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_allocations', to='course_allocation.allocationset'),
        ),
        migrations.AlterField(
            model_name='combinedcoursegroup',
            name='allocation_set',
            field=models.ForeignKey(blank=True, help_text="Which concurrent allocation this combined group belongs to. group_code used to be globally unique across the whole system, which blocked recombining the same course code in a different semester's allocation set. Now unique per allocation_set instead (see Meta.unique_together) — the same code can be reused once it's for a different set. Null only for rows created before this field existed; the backfill command attaches them to the department's legacy set.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='combined_groups', to='course_allocation.allocationset'),
        ),
        migrations.AlterField(
            model_name='courseallocation',
            name='additional_student_groups',
            field=models.ManyToManyField(blank=True, help_text="Extra StudentGroups this allocation (e.g. one lettered common-course group, EDFO 111-C) is ALSO offered to, on top of the single `student_group` above. Added for the bulk multi-group course creation flow, where one lettered group can be mapped to more than one student group at once. `student_group` stays the 'primary' group (kept for backward compatibility with every existing single-group query/filter); this field is purely additive — a group with only `student_group` set and an empty `additional_student_groups` behaves exactly as before. Use the `all_mapped_student_groups` property to read the full combined set.", related_name='additional_course_allocations', to='course_allocation.studentgroup'),
        ),
        migrations.AlterField(
            model_name='courseallocation',
            name='allocation_set',
            field=models.ForeignKey(blank=True, help_text="Which AllocationSet (concurrent allocation batch, e.g. 'Semester 1', 'Semester 2', a mixed set, or a Special allocation) this row belongs to. Null only transiently on rows created before this field existed; the backfill command (allocation_set backfill_legacy_allocation_sets) attaches every such row to a per-department 'Legacy Current Allocation' set without moving or altering the row itself. on_delete=PROTECT so an AllocationSet can never be deleted while it still holds allocations — it must be emptied or archived first.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_allocations', to='course_allocation.allocationset'),
        ),
        migrations.AlterField(
            model_name='laballocation',
            name='allocation_set',
            field=models.ForeignKey(blank=True, help_text="Which concurrent AllocationSet (e.g. Semester 1 vs Semester 2, or a Special allocation) this lab/workshop allocation belongs to. Mirrors CourseAllocation.allocation_set: a COD working in one allocation set should not see or bulk-affect another set's lab allocations, even for the same department/course. Null only for rows created before this field existed; the backfill command (allocation_set backfill_legacy_allocation_sets) attaches those to the department's legacy set.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_allocations', to='course_allocation.allocationset'),
        ),
        migrations.AlterField(
            model_name='selectiongroup',
            name='allocation_set',
            field=models.ForeignKey(blank=True, help_text="Which concurrent allocation (e.g. Semester 1 vs Semester 2) this group belongs to. A COD editing Semester 1 should not see or edit Semester 2's selection groups, and the same name may be reused across different sets. Null only for rows created before this field existed; the backfill command attaches them to the department's legacy set.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_groups', to='course_allocation.allocationset'),
        ),
        migrations.AlterField(
            model_name='specializationcategory',
            name='allocation_set',
            field=models.ForeignKey(blank=True, help_text='Which concurrent allocation this category belongs to — same reasoning as SelectionGroup.allocation_set above. Lets the same category/stem name be reused across different sets.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specialization_categories', to='course_allocation.allocationset'),
        ),
    ]
