# Generated by Django 4.2.30 on 2026-09-22 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program_management', '0007_alter_programcourse_semester'),
        ('department_management', '0003_backfill_department_codes'),
        ('course_allocation', '0024_stemstudentcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroupDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=100)),
                ('course_name', models.CharField(blank=True, default='', max_length=200)),
                ('num_groups', models.PositiveSmallIntegerField(default=1)),
                ('suggested_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('suggested_semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_group_drafts', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_group_drafts', to='department_management.department')),
            ],
            options={
                'verbose_name': 'Course Group Draft',
                'verbose_name_plural': 'Course Group Drafts',
                'ordering': ['course_code'],
                'unique_together': {('department', 'course_code')},
            },
        ),
        migrations.CreateModel(
            name='CourseGroupDraftLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=4)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='course_allocation.coursegroupdraft')),
            ],
            options={
                'verbose_name': 'Course Group Draft Letter',
                'verbose_name_plural': 'Course Group Draft Letters',
                'ordering': ['letter'],
                'unique_together': {('draft', 'letter')},
            },
        ),
        migrations.AlterField(
            model_name='groupingtemplatestemassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stemstudentcount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CourseGroupDraftMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='course_allocation.coursegroupdraft')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='course_allocation.coursegroupdraftletter')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_group_draft_mappings', to='program_management.program')),
                ('stem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_group_draft_mappings', to='course_allocation.specializationstem')),
            ],
            options={
                'verbose_name': 'Course Group Draft Mapping',
                'verbose_name_plural': 'Course Group Draft Mappings',
                'unique_together': {('letter', 'program', 'stem')},
            },
        ),
    ]
