# Generated by hand to match Django's migration format — see note in
# 0025_coursegroupdraft_coursegroupdraftletter_and_more.py (that one was
# also hand-written, no live DB/settings available in this sandbox to run
# makemigrations for real). Please sanity-check with
# `python manage.py makemigrations --check --dry-run course_allocation`
# before applying.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer_portal', '0001_initial'),
        ('course_allocation', '0025_coursegroupdraft_coursegroupdraftletter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroupdraftletter',
            name='lecturer',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='course_group_draft_letters',
                to='lecturer_portal.lecturer',
                help_text=(
                    "Lecturer assigned to THIS lettered group (e.g. 'EDFO 111-A') for the "
                    "whole course code, regardless of which program/stem it ends up mapped "
                    "to — one letter is one physical class. Settable before or after Commit; "
                    "set_letter_lecturer() keeps any already-committed CourseAllocation rows "
                    "for this letter in sync."
                ),
            ),
        ),
    ]
