# Generated by Django 4.2.30 on 2026-07-19 00:48

from django.db import migrations, models
import django.db.models.deletion
import export_import.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimetablePdfTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_logo', models.ImageField(blank=True, help_text='University logo (recommended size: 150x150px, transparent PNG preferred)', null=True, storage=export_import.models.CustomLogoStorage(), upload_to=export_import.models.logo_upload_path)),
                ('university_name', models.CharField(default='Chuka University', help_text='University name', max_length=500)),
                ('motto_latin', models.CharField(default='Sapientia divitia est', help_text='Latin motto', max_length=255)),
                ('motto_swahili', models.CharField(default='Akili ni Mali', help_text='Swahili motto', max_length=255)),
                ('directorate_name', models.CharField(default='DIRECTORATE OF EXAMINATIONS AND TIMETABLING', help_text='Directorate name', max_length=500)),
                ('telephone', models.CharField(default='020-2310512/18', help_text='Telephone number', max_length=100)),
                ('address', models.CharField(default='P. O. Box 109-60400, Chuka', help_text='Physical address', max_length=500)),
                ('email', models.EmailField(default='extt@chuka.ac.ke', help_text='Contact email', max_length=254)),
                ('website', models.URLField(default='https://www.chuka.ac.ke', help_text='University website')),
                ('reference_prefix', models.CharField(default='Ref: CU/EXTT/', help_text='Prefix for reference numbers', max_length=100)),
                ('title_format', models.CharField(default='{timetable_type} Timetable', help_text='Title format. Use {timetable_type} placeholder', max_length=500)),
                ('page_header_format', models.CharField(default='{timetable_type} Page {page} of {total_pages}', help_text='Page header format', max_length=500)),
                ('notes', models.TextField(default='NB: All queries to be channeled via email address (extt@chuka.ac.ke) or visit the office at Science Complex (S102)', help_text='Important notes/instructions at bottom')),
                ('key_section', models.TextField(default="KEY: \n- PAV H (PAVILION HALL UPSTAIRS)\n- MSH 03 - 10 (MALE STUDENTS' HOSTEL COMMON ROOMS)\n- MS (01- 34) - MEDIA SCHOOL COMPLEX\n- S (SGT1 - S602) - SCIENCE COMPLEX\n- BSL (BSL 001- 503) BUSINESS SCHOOL LEFT WING\n- BSR (BSR 001- 503) BUSINESS SCHOOL RIGHT WING\n- LLB 1- 3: FACULTY OF LAW (BSRC COMPLEX)\n- L1 - L4: AREA NEAR EGERTON HOUSE\n- FTC B01 - FTC 605: FOOD TECHNOLOGY CENTRE\n- SRP B 01- SRP 305: SCIENCE RESEARCH PARK COMPLEX", help_text='Key/legend for room codes')),
                ('prepared_by_label', models.CharField(default='Prepared by:', help_text='Label for prepared by section', max_length=100)),
                ('director_label', models.CharField(default='Director (Examinations and Timetabling)', help_text='Label for director signature', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timetable PDF Template',
                'verbose_name_plural': 'Timetable PDF Template',
            },
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the document (e.g., '2024/2025 1st Semester Examination Timetable')", max_length=200)),
                ('document_type', models.CharField(choices=[('EXAM', 'Examination Timetable'), ('REGULAR', 'Regular Timetable')], help_text='Type of timetable document', max_length=20)),
                ('pdf_file', models.FileField(help_text='Upload the PDF document', upload_to='timetables/pdfs/%Y/%m/%d/')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('academic_year', models.CharField(help_text='e.g., 2024/2025', max_length=15)),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester')], max_length=2)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of the document')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('uploaded_by', models.CharField(blank=True, help_text='Name or username of the person who uploaded the document', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Brief description or notes about this document')),
                ('is_latest', models.BooleanField(default=True, help_text='Is this the latest version of this document type for this academic year/semester?')),
                ('previous_version', models.ForeignKey(blank=True, help_text='Previous version of this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_version', to='export_import.pdfdocument')),
            ],
            options={
                'verbose_name': 'PDF Document',
                'verbose_name_plural': 'PDF Documents',
                'ordering': ['-uploaded_at'],
                'permissions': [('can_upload_pdf', 'Can upload PDF documents'), ('can_publish_pdf', 'Can publish PDF documents'), ('can_archive_pdf', 'Can archive PDF documents')],
                'indexes': [models.Index(fields=['academic_year', 'semester', 'document_type'], name='export_impo_academi_921ef0_idx'), models.Index(fields=['status', 'uploaded_at'], name='export_impo_status_09ae34_idx'), models.Index(fields=['is_latest'], name='export_impo_is_late_5860fc_idx')],
            },
        ),
    ]
